### ISSUE TITLE
Files with "-"s in their name can be a security flaw

### ISSUE THREAD

**Issue by AI221** [dimgel/cpp-linux-scripts#1]
Here's my scenerio. You have a cpp script file at ~/securedir/script.cpp  . You run it as root at startup.

I'm a malicious person, and I want to gain root privileges next time you boot your system. I make a file at your home directory, and call it ~/securedir--script.cpp then run it. Next time you boot your system, you'll run my code as root. 

Additionally, if I do this:

$ ./script.cpp
\# ./script.cpp #note the running as root

The compiled file still has user permissions, so I may now go and modify it and put my malicous code in.

I'd suggest making seperate files for each user, as well as making sure the compiled file is owned by your user. In the file name, replace normal "-"s with "---" (you can't have a directory named "", so this is a weird solution but I think it would work)

Overall nice program. I'm sure security is not #1 with this small project, but it's always good to write secure programs anyway.

**Comment by dimgel** [comment]
I know global compiled cache was bad idea. :) Will update docs with this recommendation; only need to think up good wording - that README is already larger than program itself. :))

Still, considering root scripts specifically: if script is to be run as root then I believe root should own its source code, i.e. "~" == "/root': /root/securedir/script.cpp. Then compiled file will be /usr/local/bin/build-n-run.compiled/root--securedir--script and it will be owned by root too and only root will have write permissions on it, so other user won't be able overwrite it.

**Comment by dimgel** [comment]
Now compiled cache is created inside user's home; docs updated.
